feat: dashboard
atls/orbitto pull request #19
Opened 2022-08-17 17:41 UTC by brusselboy

2022-08-19 18:45 UTC, TFK70 requested changes

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/messages.ts
> +export default defineMessages({
Инить локали так же как это было на VSBLE:

https://github.com/torin-asakura/VSBLE/blob/master/site/fragments/navigation/src/navigation.component.tsx#L95

https://github.com/torin-asakura/VSBLE/blob/master/site/entrypoints/renderer/locales/en.json

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/messages.ts
> +    defaultMessage: '490P в месяц',
Цена будет динамической

У нас есть сущность - подписка, у нее есть цена, эти данные будут идти с бэка

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/messages.ts
> +    defaultMessage: 'name@email.com',
Тоже динамик данные

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/profile-popover/profile-popover.component.tsx
> +const ProfilePopover: FC = () => {
Просто Profile

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/profile-popover/profile-popover.component.tsx
> +      {render(
А это лучше вынести в компонент Menu

Но не создавай под него отдельную директорию, а то адовая вложенность будет

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/profile-popover/profile-popover.component.tsx
> +  const date = intl.formatDate(new Date('2022-05-30'), dateOptions)
Тоже динамик данные

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/header/src/profile-popover/profile-popover.component.tsx
> +  const dateOptions = { year: 'numeric', month: '2-digit', day: '2-digit' } as const
Используй Object.freeze если это иммутабельный объект

2022-08-19 18:45 UTC, TFK70 commented on dashboard/fragments/navigation/src/navigation.component.tsx
> +                style={{ height: 20 }}
У него же вроде weight должен за это отвечать?

2022-08-19 18:45 UTC, TFK70 commented on ui/button/src/styles/appearance/appearance.styles.ts
> +import { styleFn }                    from 'styled-system'
Используй [генератор](https://github.com/atls/uikit/tree/master/generators)
[Пример](https://github.com/TFK70/banxe-poc/tree/master/ui/button) (репа приватная, кинул инвайт)

2022-08-19 18:45 UTC, TFK70 commented on ui/modal/src/container/base/base.styles.ts
> +  zIndex: 9999,
zIndex 9999 лучше избегать
Поставь какой-нибудь zIndex 100, до 1000 в общем

2022-08-19 18:45 UTC, TFK70 commented on ui/text/src/text.component.tsx
> +Text.defaultProps = {
А зачем надо было весь компонент реинитить?

Так не вышло?

```typescript
import { Text } from ‘@atls-ui-parts/text’

Text.defaultProps = {
   ...Text.defaultProps,
   color: inherit
}

export * from '@atls-ui-parts/text'
export { Text }
```

2022-08-19 18:45 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +          background-color: #F5F5F5;
Импортни цвет из темы напрямую: import theme from './theme'

2022-08-22 10:50 UTC, TFK70 requested changes

2022-08-22 10:50 UTC, TFK70 commented on dashboard/fragments/header/src/header.component.tsx
> +      <Box
Вынеси это тоже в отдельный компонент

Так выглядит не очень, ты здесь где-то инитишь компоненты as-it, а где-то выносишь в сущности как в Profile. Декомпозируй это и собери Header чисто из сущностей

2022-08-22 10:50 UTC, TFK70 commented on dashboard/fragments/header/src/header.component.tsx
> +      <Box
Плюс ты будешь фетчить последнее время обновления, это тоже лучше инкапсулировать внутри компонента, а не писать в хедере

2022-08-22 12:41 UTC, TFK70 approved these changes

2022-08-22 16:39 UTC, TorinAsakura approved these changes

2022-08-22 16:39 UTC, merged