feat: ligaments
atls/orbitto pull request #26
Opened 2022-08-29 19:02 UTC by brusselboy

2022-08-31 14:57 UTC, TFK70 requested changes
1. У слайсов в дэшд-бордере слишком маленький спейс:

![image](https://user-images.githubusercontent.com/62806448/187708695-cd45660f-7234-4736-ae5f-151e31257187.png)

Скорее всего хакать надо будет, но это гуглится

2. Эта анимация на большом разрешении слишком лагучая, тем более если в скрытых лигаментах будет много итемов - в анимации смысла не будет совсем. Так что сделай топорную отрисовку без анимации

https://user-images.githubusercontent.com/62806448/187709541-d7cead49-4475-46cd-a515-a2070b3a9d36.mov

3. Не вижу чтобы что-то менялось когда я меняю сортировку (по порядку/лучшие спреды). У тебя на фронте меняется логика отображения в зависимости от метода сортировки: на лучших спредах связки не подразделяются на методы оплаты и там нету кнопки "показать больше"
4. Логика с блюром связки тоже реализована?

![image](https://user-images.githubusercontent.com/62806448/187710467-24332d0b-6044-4ce1-9021-d2e005c675c4.png)

2022-08-31 14:57 UTC, TFK70 commented on ui/theme/src/theme/borders.ts
> +  grayDashed: '0.625px dashed rgba(192, 194, 203, 0.5)',
1.25px же должно быть?

2022-09-01 12:39 UTC, brusselboy commented
@TFK70 логика с блюром находится в этой [задаче](https://github.com/atls/orbitto/issues/9), может лучше отдельным ПРом её сделать?

2022-09-02 17:57 UTC, TFK70 approved these changes

2022-09-06 10:56 UTC, TorinAsakura approved these changes

2022-09-06 10:56 UTC, merged